name: file-chatbot
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.9
  - faiss-cpu
  - pip
  - pip:
      - streamlit
      - langchain
      - langchain-community
      - langchain-openai
      - openai
      - pypdf
      - tiktoken
      - requests
